name: 问题报告
description: 遇到错误请在此报告。
labels: [BUG]

body:
  - type: markdown
    attributes:
      value: |
        提交前请先搜索现有 issue，并使用能够概括问题的标题。重复问题、缺少必要信息或仅存在于旧版本的问题可能会被关闭。

        功能建议请[开启空 issue](https://github.com/STERILITZIA02/Bewly_Nocturne/issues/new)，不要填写此问题报告。

        若问题只在特定页面出现，请一并附上页面链接。

  - type: textarea
    attributes:
      label: 环境信息
      description: 【请勿修改 issue 模版。】扩展版本、浏览器版本、以及你做出的自定义设置。
      value: |
        - 浏览器（如 Google Chrome）：
        - 浏览器版本（如 126.0.6478.126）：
        - Bewly_Nocturne 版本（如 1.7.4）：

        如果修改过 Bewly_Nocturne 设置，请简要说明相关设置项：

    validations:
      required: true

  - type: dropdown
    attributes:
      label: 安装来源
      options:
        - 插件商店
        - GitHub
        - 自行编译
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 如何重现，最好带有截图或视频以便排查。
      placeholder: |
        请预先搜索此问题是否在其他 issue 中出现过
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期行为
      description: 你认为应该是什么行为。
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 最终确认
      description: 请先排除 Bilibili、浏览器和其他扩展导致的问题，再完成以下确认。
      options:
        - label: 我确认在停用 Bewly_Nocturne 并强制刷新（按住 Shift 键的同时按刷新键）后，问题不再出现。
          required: false
        - label: 我确认此问题未在其他 issue 中出现过。
          required: false
        - label: 我确认我正在使用最新的 Bewly_Nocturne 版本。
          required: false

  - type: checkboxes
    attributes:
      label: 参与贡献
      options:
        - label: 我愿意自行创建 PR 修复此问题
          required: false
